def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    
	agent any
    tools {
        maven "MAVEN3"
        jdk "JAVA_HOME"
    }
	environment {
        cluster = "vprofile-prod-cluster"
        service = "vprofile-prod-svc"
    }
    



    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#vprofile-app',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}    


        




